name: LocationLog
version: '${project.version}'
main: com.github.bitbyte.locationlog.LocationLog
api-version: 1.19
author: 1BitByte
permissions:
  locationlog.viewlog:
    description: Players with this permission get sent the location logs. This can result in spammy messages
    default: false
  locationlog.exempt:
    description: Players with this permission are exempt from the logging
    default: false
commands:
  loglocations:
    aliases:
      - locations
      - forcelog
    permission: locationlog.forcelog
  logadd:
    permission: locationlog.listadd
  logremove:
    permission: locationlog.listremove
  setlisttype:
    aliases:
      - changelisttype
    permission: locationlog.setlisttype