name: LocationLog
version: '${project.version}'
main: com.github.bitbyte.locationlog.LocationLog
api-version: 1.19
commands:
  loglocations:
    aliases:
      - forcelocations
      - locations
      - forcelog
    permission: locationlog.forcelog